## DATA PREPROCESSING AND DATA CLEANING

In [1]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv('cyber.csv')
df.tail()

,Fwd_Packet_Length_Mean,Fwd_Packet_Length_Std,Bwd_Packet_Length_Max,Bwd_Packet_Length_Min,Bwd_Packet_Length_Mean,Bwd_Packet_Length_Std,Fwd_IAT_Total,Fwd_IAT_Mean,Fwd_IAT_Std,Fwd_IAT_Max,...,FWD_Init_Win_Bytes,Bwd_Init_Win_Bytes,Fwd_Act_Data_Pkts,Fwd_Seg_Size_Min,Active_Mean,Active_Std,Active_Max,Active_Min,Label,Connection_Type
138390,32.0,0.0,60,60,60.0,0.0,0,0.0,0.0,0,...,0,0,0,8,0.0,0.0,0,0,UDP Flood,0
138391,41.0,0.0,41,41,41.0,0.0,0,0.0,0.0,0,...,0,0,0,8,0.0,0.0,0,0,UDP Flood,0
138392,43.0,0.0,97,97,97.0,0.0,0,0.0,0.0,0,...,0,0,0,8,0.0,0.0,0,0,UDP Flood,0
138393,47.0,0.0,63,63,63.0,0.0,0,0.0,0.0,0,...,0,0,0,8,0.0,0.0,0,0,UDP Flood,1
138394,34.0,0.0,79,79,79.0,0.0,0,0.0,0.0,0,...,0,0,0,8,0.0,0.0,0,0,UDP Flood,0

In [3]:
df.shape

(138395, 43)

In [4]:
df.size

5950985

In [5]:
df.columns

Index(['Fwd_Packet_Length_Mean', 'Fwd_Packet_Length_Std',
       'Bwd_Packet_Length_Max', 'Bwd_Packet_Length_Min',
       'Bwd_Packet_Length_Mean', 'Bwd_Packet_Length_Std', 'Fwd_IAT_Total',
       'Fwd_IAT_Mean', 'Fwd_IAT_Std', 'Fwd_IAT_Max', 'Fwd_IAT_Min',
       'Bwd_IAT_Total', 'Bwd_IAT_Mean', 'Bwd_IAT_Std', 'Bwd_IAT_Max',
       'Fwd_PSH_Flags', 'Fwd_URG_Flags', 'Fwd_Header_Length',
       'Bwd_Header_Length', 'Fwd_Packets/s', 'Bwd_Packets/s',
       'Packet_Length_Std', 'Packet_Length_Variance', 'CWR_Flag_Count',
       'Fwd_Packet/Bulk_Avg', 'Fwd_Bulk_Rate_Avg', 'Bwd_Bytes/Bulk_Avg',
       'Bwd_Packet/Bulk_Avg', 'Bwd_Bulk_Rate_Avg', 'Subflow_Fwd_Packets',
       'Subflow_Fwd_Bytes', 'Subflow_Bwd_Packets', 'Subflow_Bwd_Bytes',
       'FWD_Init_Win_Bytes', 'Bwd_Init_Win_Bytes', 'Fwd_Act_Data_Pkts',
       'Fwd_Seg_Size_Min', 'Active_Mean', 'Active_Std', 'Active_Max',
       'Active_Min', 'Label', 'Connection_Type'],
      dtype='object')

In [6]:
df.isnull()

,Fwd_Packet_Length_Mean,Fwd_Packet_Length_Std,Bwd_Packet_Length_Max,Bwd_Packet_Length_Min,Bwd_Packet_Length_Mean,Bwd_Packet_Length_Std,Fwd_IAT_Total,Fwd_IAT_Mean,Fwd_IAT_Std,Fwd_IAT_Max,...,FWD_Init_Win_Bytes,Bwd_Init_Win_Bytes,Fwd_Act_Data_Pkts,Fwd_Seg_Size_Min,Active_Mean,Active_Std,Active_Max,Active_Min,Label,Connection_Type
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138390,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
138391,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
138392,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
138393,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
138394,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [7]:
df = df.dropna()

In [8]:
df.describe()

,Fwd_Packet_Length_Mean,Fwd_Packet_Length_Std,Bwd_Packet_Length_Max,Bwd_Packet_Length_Min,Bwd_Packet_Length_Mean,Bwd_Packet_Length_Std,Fwd_IAT_Total,Fwd_IAT_Mean,Fwd_IAT_Std,Fwd_IAT_Max,...,Subflow_Bwd_Bytes,FWD_Init_Win_Bytes,Bwd_Init_Win_Bytes,Fwd_Act_Data_Pkts,Fwd_Seg_Size_Min,Active_Mean,Active_Std,Active_Max,Active_Min,Connection_Type
count,138395.000000,138395.000000,138395.000000,138395.000000,138395.000000,138395.000000,1.383950e+05,1.383950e+05,1.383950e+05,1.383950e+05,...,138395.000000,138395.000000,138395.000000,138395.000000,138395.000000,1.383950e+05,1.383950e+05,1.383950e+05,1.383950e+05,138395.000000
mean,20.518853,22.211238,57.723856,9.395202,20.238152,15.665406,4.839415e+06,2.679528e+06,5.401937e+05,3.401314e+06,...,9.638079,8827.725207,499.151797,1.233166,19.650045,1.216110e+05,3.321799e+04,1.526796e+05,9.683433e+04,0.660349
std,120.279917,221.722094,580.275784,35.956532,139.034576,160.598285,1.052599e+07,6.034829e+06,2.373440e+06,7.251761e+06,...,75.896932,18396.638304,3946.756317,84.073490,10.175941,9.402362e+05,3.891432e+05,1.127954e+06,8.645230e+05,0.473592
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000,0.000000,0.000000,0.000000,8.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000,1024.000000,0.000000,0.000000,24.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000
75%,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.118951e+06,1.559363e+06,1.663807e+03,2.082812e+06,...,0.000000,1024.000000,0.000000,1.000000,24.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000
max,8534.697356,7241.921811,61560.000000,2248.000000,8542.357508,7354.317317,6.057185e+07,5.898142e+07,4.217559e+07,5.990522e+07,...,6088.000000,65535.000000,65535.000000,27910.000000,44.000000,5.244013e+07,2.360479e+07,5.244013e+07,5.244013e+07,1.000000

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 138395 entries, 0 to 138394
Data columns (total 43 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Fwd_Packet_Length_Mean  138395 non-null  float64
 1   Fwd_Packet_Length_Std   138395 non-null  float64
 2   Bwd_Packet_Length_Max   138395 non-null  int64
 3   Bwd_Packet_Length_Min   138395 non-null  int64
 4   Bwd_Packet_Length_Mean  138395 non-null  float64
 5   Bwd_Packet_Length_Std   138395 non-null  float64
 6   Fwd_IAT_Total           138395 non-null  int64
 7   Fwd_IAT_Mean            138395 non-null  float64
 8   Fwd_IAT_Std             138395 non-null  float64
 9   Fwd_IAT_Max             138395 non-null  int64
 10  Fwd_IAT_Min             138395 non-null  int64
 11  Bwd_IAT_Total           138395 non-null  int64
 12  Bwd_IAT_Mean            138395 non-null  float64
 13  Bwd_IAT_Std             138395 non-null  float64
 14  Bwd_IAT_Max             138395 non-null  int64
 15  Fwd_PSH_Flags           138395 non-null  int64
 16  Fwd_URG_Flags           138395 non-null  int64
 17  Fwd_Header_Length       138395 non-null  int64
 18  Bwd_Header_Length       138395 non-null  int64
 19  Fwd_Packets/s           138395 non-null  float64
 20  Bwd_Packets/s           138395 non-null  float64
 21  Packet_Length_Std       138395 non-null  float64
 22  Packet_Length_Variance  138395 non-null  float64
 23  CWR_Flag_Count          138395 non-null  int64
 24  Fwd_Packet/Bulk_Avg     138395 non-null  int64
 25  Fwd_Bulk_Rate_Avg       138395 non-null  int64
 26  Bwd_Bytes/Bulk_Avg      138395 non-null  int64
 27  Bwd_Packet/Bulk_Avg     138395 non-null  int64
 28  Bwd_Bulk_Rate_Avg       138395 non-null  int64
 29  Subflow_Fwd_Packets     138395 non-null  int64
 30  Subflow_Fwd_Bytes       138395 non-null  int64
 31  Subflow_Bwd_Packets     138395 non-null  int64
 32  Subflow_Bwd_Bytes       138395 non-null  int64
 33  FWD_Init_Win_Bytes      138395 non-null  int64
 34  Bwd_Init_Win_Bytes      138395 non-null  int64
 35  Fwd_Act_Data_Pkts       138395 non-null  int64
 36  Fwd_Seg_Size_Min        138395 non-null  int64
 37  Active_Mean             138395 non-null  float64
 38  Active_Std              138395 non-null  float64
 39  Active_Max              138395 non-null  int64
 40  Active_Min              138395 non-null  int64
 41  Label                   138395 non-null  object
 42  Connection_Type         138395 non-null  int64
dtypes: float64(14), int64(28), object(1)
memory usage: 45.4+ MB

In [10]:
df['Label'].unique()

array(['Benign', 'DNS Flood', 'ICMP Flood', 'OS Scan', 'Ping Sweep',
       'Port Scan', 'SYN Flood', 'Slowloris', 'UDP Flood'], dtype=object)

In [11]:
df['Label'].value_counts()

Label
Benign        20000
ICMP Flood    20000
OS Scan       20000
Ping Sweep    20000
Port Scan     20000
Slowloris     18643
SYN Flood     13857
DNS Flood      5104
UDP Flood       791
Name: count, dtype: int64

In [12]:
pd.Categorical(df["Label"]).describe()

            counts     freqs
categories
Benign       20000  0.144514
DNS Flood     5104  0.036880
ICMP Flood   20000  0.144514
OS Scan      20000  0.144514
Ping Sweep   20000  0.144514
Port Scan    20000  0.144514
SYN Flood    13857  0.100126
Slowloris    18643  0.134709
UDP Flood      791  0.005716

In [13]:
df.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
138390    False
138391    False
138392    False
138393    False
138394    False
Length: 138395, dtype: bool

In [14]:
df = df.drop_duplicates()

In [15]:
sum(df.duplicated())

0